#!/bin/bash
# project-kb Git Cleanup Script
# Run this in Mac Terminal to remove legacy ChatGPT-generated files from git tracking.
# Created: 22/04/2026

set -e  # exit on any error

REPO=~/Desktop/avid-knowledge-base/project-kb

echo "=== Step 1: Remove index.lock if present ==="
[ -f "$REPO/.git/index.lock" ] && rm "$REPO/.git/index.lock" && echo "Removed index.lock" || echo "No lock file found"

echo ""
echo "=== Step 2: Change to repo directory ==="
cd "$REPO"
echo "Working in: $(pwd)"

echo ""
echo "=== Step 3: Remove Stream IO and production-management ==="
git rm --ignore-unmatch avid-stream-io_2025.2_whats-new.md avid-stream-io_2025.6_whats-new.md
git rm -r --ignore-unmatch production-management
git rm -r --ignore-unmatch "📄 production-management"

echo ""
echo "=== Step 4: Remove legacy Media Composer versions ==="
git rm -r --ignore-unmatch \
  media-composer/2021.12 \
  media-composer/2022.10 \
  media-composer/2022.12 \
  media-composer/2022.4 \
  media-composer/2022.7 \
  media-composer/2023.12 \
  media-composer/2023.3 \
  media-composer/2023.8 \
  media-composer/2024.10 \
  media-composer/2024.12 \
  media-composer/2024.2 \
  media-composer/2024.6 \
  media-composer/2025.12 \
  media-composer/2025.6

echo ""
echo "=== Step 5: Remove legacy NEXIS versions ==="
git rm -r --ignore-unmatch \
  nexis/2022.12 \
  nexis/2022.5 \
  nexis/2022.9 \
  nexis/2023.0 \
  nexis/2023.12 \
  nexis/2023.8 \
  nexis/2023.8.1 \
  nexis/2024.10 \
  nexis/2024.11 \
  nexis/2024.2 \
  nexis/2024.5 \
  nexis/2024.6 \
  nexis/2024.6.1 \
  nexis/2024.6.2 \
  nexis/2025.10 \
  nexis/2025.2 \
  nexis/2025.2.2 \
  nexis/2025.3 \
  nexis/2025.5 \
  nexis/2025.5.1 \
  nexis/2025.5.3
git rm -r --ignore-unmatch "nexis/Avid NEXIS 2022.12.0 – New Features"

echo ""
echo "=== Step 6: Remove legacy MediaCentral Cloud UX versions ==="
git rm -r --ignore-unmatch \
  mediacentral/cloud-ux/2022.12 \
  mediacentral/cloud-ux/2023.12 \
  mediacentral/cloud-ux/2023.7 \
  mediacentral/cloud-ux/2024.10 \
  mediacentral/cloud-ux/2024.2 \
  mediacentral/cloud-ux/2025.10 \
  mediacentral/cloud-ux/2025.6

echo ""
echo "=== Step 7: Remove legacy MediaCentral Newsroom Management versions ==="
git rm -r --ignore-unmatch \
  mediacentral/newsroom-management/2022.3 \
  mediacentral/newsroom-management/2023.3 \
  mediacentral/newsroom-management/2023.7 \
  mediacentral/newsroom-management/2024.10 \
  mediacentral/newsroom-management/2024.10.4 \
  mediacentral/newsroom-management/2024.10.5

echo ""
echo "=== Step 8: Remove mediacentral/mediacentral ==="
git rm -r --ignore-unmatch mediacentral/mediacentral

echo ""
echo "=== Step 9: Commit ==="
git commit -m "chore: remove legacy ChatGPT-generated files from git tracking

Removes all legacy versioned content that was generated by ChatGPT
and does not meet project-kb standards. Retains current Tamaniu-built
structure only."

echo ""
echo "=== Step 10: Push ==="
git push

echo ""
echo "=== Done! Now regenerate MANIFEST.txt ==="
echo "Run the MANIFEST regeneration step, or ask Claude to do it in Cowork."
